name: ci
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            arch: x64
            gen_short_name: "vs17_2022"
            gen_cmake_name: "Visual Studio 17 2022"

          - os: ubuntu-22.04
            arch: x64
            cc: gcc
            cxx: g++

          - os: macos-12
            arch: x86_64
            gen: Xcode

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Deps (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update -y
        sudo apt-get install gcc libcriterion-dev cmake meson ninja-build libgit2-dev libffi-dev -y
        git clone https://github.com/Snaipe/Criterion.git --recursive
        cd Criterion
        meson setup -Dc_std=gnu11 --prefix /usr/local --libdir lib --buildtype plain --force-fallback-for libffi --wrap-mode nodownload build
        meson compile -C build
        sudo meson install -C build

    - name: Install Deps (Windows)
      if: ${{ matrix.os == 'windows-2022' }}
      run: |
        choco install cmake meson ninja
        git clone https://github.com/Snaipe/Criterion.git --recursive
        cd Criterion
        meson setup -Dc_std=c11 --prefix /usr/local --libdir lib --buildtype plain --force-fallback-for libffi --wrap-mode nodownload build
        meson compile -C build
        meson install -C build

    - name: Install Deps (MacOS)
      if: ${{ matrix.os == 'macos-12' }}
      run: brew install criterion

    - name: Generate Build Files & Build (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        export CC=${{ matrix.cc }}
        export CXX=${{ matrix.cxx }}
        export CXXFLAGS=${{ matrix.flags }}
        export CFLAGS=${{ matrix.flags }}
        export LDFLAGS=${{ matrix.flags }}
        make all GENERATOR=Ninja BUILD_TYPE=Release NUM_JOBS=4

    - name: Generate Build Files & Build (Windows)
      if: ${{ matrix.os == 'windows-2022' }}
      run: |
        make all GENERATOR="${{ matrix.gen_cmake_name }}" BUILD_TYPE=Release NUM_JOBS=4 CMAKE_GEN_FLAGS='-A "${{ matrix.arch }}" -T "ClangCL"'

    - name: Generate Build Files, Build & Zip (MacOS)
      if: ${{ matrix.os == 'macos-12' }}
      run: |
        make all GENERATOR="${{ matrix.gen }}" BUILD_TYPE=Release NUM_JOBS=4 CMAKE_GEN_FLAGS='-DBUILD_APPLE_BUNDLE=ON -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}'

    - name: Run Test (Windows)
      if: ${{ matrix.os == 'windows-2022' }}
      run: ./build/Release/FileSystem_Test.exe

    - name: Run Test (Non-Windows)
      if: ${{ matrix.os != 'windows-2022' }}
      run: ./build/FileSystem_Test

    - name: Upload Artifacts (Linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      uses: actions/upload-artifact@v3
      with:
        name: linux-${{ matrix.arch }}
        if-no-files-found: error
        path: ./build/

    - name: Upload artifacts (Windows)
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'windows-2022' }}
      with:
        name: win-${{ matrix.arch }}
        if-no-files-found: error
        path: ./build/

    - name: Upload Artifacts (MacOS)
      uses: actions/upload-artifact@v3
      if: ${{ matrix.os == 'macos-12' }}
      with:
        name: osx-${{ matrix.arch }}
        if-no-files-found: error
        path: ./build/

